# Generated by Django 4.2.4 on 2024-04-10 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_registration_no', models.CharField(max_length=10)),
                ('veh_model', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('vehicle_category', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_model', models.CharField(max_length=255)),
                ('veh_registration_no', models.CharField(max_length=10)),
                ('parking_rate', models.PositiveIntegerField()),
                ('intime', models.DateTimeField(auto_now_add=True)),
                ('outtime', models.DateTimeField()),
                ('fee', models.FloatField()),
                ('vehicle_type', models.CharField(choices=[('4', '4-wheeler'), ('3', '3-wheeler'), ('2', '2-wheeler')], default='2', max_length=50)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
