# Generated by Django 4.2.4 on 2024-04-17 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aapniparking', '0003_parkingbookslot_parkingspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingbookslot',
            name='parking_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingbookslot',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkingbookslot',
            name='owner_contactno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parkingbookslot',
            name='vehicle_uniqueid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_uniqueid', to='aapniparking.vehicle'),
        ),
    ]
