# Generated by Django 4.2.4 on 2024-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapniparking', '0005_alter_parkingbookslot_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='parked',
            field=models.BooleanField(default=False),
        ),
    ]
