# Generated by Django 4.2.4 on 2024-04-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0003_emailsender_date_emailsender_ques'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sym', models.CharField(max_length=50)),
                ('stockprice', models.PositiveIntegerField()),
            ],
        ),
    ]
