# Generated by Django 4.2.4 on 2024-03-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
