# Generated by Django 4.2.4 on 2024-03-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_doctor_ap_date_doctor_fees_doctor_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doc_fee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='hospital.doctor'),
        ),
    ]
