# Generated by Django 4.2.4 on 2024-03-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_appointment_doc_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_ap_date',
            field=models.DateField(auto_now=True),
        ),
    ]
