# Generated by Django 4.2.4 on 2024-03-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_doctor_doctor_ap_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doc_fee',
            field=models.IntegerField(default=350),
        ),
    ]
